name: Generate prerelease
on:
  push:
    branches:
      - develop
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ci_cd_1

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: git config --global user.email "robotino@example.com"
      - run: git config --global user.name "MODO CI Robot"
      - run: npm install
      - run: npm run release -- --prerelease rc
      - run: git push --follow-tags
