# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      version:
        description: Base tag (default -> last "develop" tag)
        required: false
        default: develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-release:
    name: Create prerelease tag.
    runs-on: ubuntu-latest
    env:
      APP_NAME: ci_cd_1
    outputs:
      package_version: ${{ steps.set_package.outputs.package_version }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - name: Generate deploy tag
        run: |
          ls .github
          sh .github/check-ff.sh
          git checkout $INPUT_VERSION
          git config --global user.email "robotino@example.com"
          git config --global user.name "MODO CI Robot"
          npm install standard-version
          npm run release
      - name: Deploy to prod
        run: echo "Deploy to prod"
      - name: Create tag
          git push --follow-tags --no-verify
      - name: Merge to main branch
          git push origin main
