name: Merge to master
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ci_cd_1

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: git config --global user.email "robotino@example.com"
      - run: git config --global user.name "Thaddeus Robotino"
      - run: npm install
      - run: npm run release
      - run: git push --follow-tags
      - name: Get changelog diff
        id: get_last_changelog
        run: |
          str="$(awk '/### 1/{flag=1;next}/### 1/{print;flag=0}flag' ./CHANGELOG.md)"
          project_ver= "$(jq -r '.name' package.json)"
          echo ::set-output name=body::${str}
          echo ::set-output name=project_ver::${str}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_last_changelog.outputs.project_ver }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.get_last_changelog.outputs.body }}
          draft: false
          prerelease: false
