name: Deploy prerelease

on:
  push:
    tags:
      - "*-pre*"

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ci_cd_1

    steps:
      - uses: develop
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: echo "Automatic deploy to QA"
