name: Share
on:
  push:
    branches:
      - feat/*
jobs:
  create-prerelease-share:
    name: Create prerelease tag.
    runs-on: ubuntu-latest
    env:
      APP_NAME: ci_cd_1
    outputs:
      output1: ${{ steps.step2.outputs.package_version }}

    steps:
      - id: step1
        uses: actions/checkout@v2
        name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '12.18'
      - id: step2
        run: |
          export CI_PACKAGE_VERSION=`node -p -e "require('./package.json').version"`
          echo "::set-output name=package_version::$CI_PACKAGE_VERSION"
  deploy-qa-share:
    name: deploy to qa
    needs: create-prerelease-share
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{needs.create-prerelease-share.outputs.output1}}

