# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-prerelease:
      name: Get tag
      runs-on: ubuntu-latest
      outputs:
        package_version: ${{ steps.set_package.outputs.package_version }}
      steps: 
        - id: set_package
          run: |
            export CI_PACKAGE_VERSION=`echo 1.2.0-rc.6`
            echo "::set-output name=package_version::v$CI_PACKAGE_VERSION"
  deploy-qa:
        name: Deploy to qa
        needs: create-prerelease
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
              ref: ${{needs.create-prerelease.outputs.package_version}}
              fetch-depth: 0  
          - run: echo ${{needs.create-prerelease.outputs.package_version}}
          - name: Use Node.js
            uses: actions/setup-node@v1
            with:
              node-version: '12.18'
          - run: git describe --tags --exact-match
